### ISSUE TITLE
Handle `autostart-tray`

### ISSUE THREAD

**Issue by gbraad** [crc-org/tray-electron#116]
* Exit the tray on start when `autostart-tray` is set to `false`?
  * Need configuration item?

**Comment by anjannath** [comment]
`autostart-tray` config option is very much tied to `crc setup` it was meant to be used with it, the handler for this config is at: https://github.com/code-ready/crc/blob/6ff0170104e74acbee36d492969b3db1eb3eaf08/pkg/crc/config/settings.go#L52-L63

in the current native trays, you can only change this option from the tray, but unless user runs the `crc cleanup` and `crc setup` it doesn't produce any effects.

**Comment by anjannath** [comment]
### Tasks
- [x] remove the `autostart-tray` config option from crc (https://github.com/code-ready/crc/pull/3009)
- [x] remove preflights that setup tray autostart from crc (^^)
- [x] remove the autostart part from windows msi (^^)
- [x] handle setting autostart from the tray during on-boarding
- [x] add config option for enable/disable autostart

**Comment by gbraad** [comment]
@anjannath finished, right?

**Comment by anjannath** [comment]
@gbraad Yes, all are done closing!
